FactoryBot.define do
  factory :api_key do
    sequence(:email) { |n| "user#{n}@example.com" }
    # token is auto-generated by model callback

    trait :with_custom_email do
      transient do
        custom_email { 'custom@example.com' }
      end

      email { custom_email }
    end
  end
end
