FactoryBot.define do
  factory :booking do
    association :api_key
    association :flight
    association :seat

    passenger_name { Faker::Name.name }
    status { 'confirmed' }
    # reference is auto-generated by model callback

    trait :confirmed do
      status { 'confirmed' }
    end

    trait :cancelled do
      status { 'cancelled' }
    end

    trait :with_available_seat do
      after(:build) do |booking|
        booking.seat ||= create(:seat, :available, flight: booking.flight)
      end
    end
  end
end
